### ISSUE TITLE
double spend tx causing balance update issues

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#1007]
When a double spend is encountered, nodes update the balance of the double spend account differently.

- Marcin double checked and was unable to reproduce, but making a note to retry once more after changes to be sure.

**Comment by marcinwadon** [comment]
I'm trying to reproduce it and I'm not able to do so.

- [x] I've wrote tests but all are passing
- [x] I've sent the same transaction twice via the load balancer (most likely same node), second transaction is invalid
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/4959931/77769738-83d3bc00-7044-11ea-901b-cb1394c35f4e.png">

- [x] I've sent the same transaction to two different nodes, second transaction is invalid
<img width="821" alt="image" src="https://user-images.githubusercontent.com/4959931/77771857-8b489480-7047-11ea-925b-477341f55442.png">
