### ISSUE TITLE
Disallow putting transaction to the cluster if the reference is incorrect

### ISSUE THREAD

**Issue by marcinwadon** [Constellation-Labs/constellation#1015]
To avoid stuck tx in the pending state, if the tx reference is incorrect we shouldn't allow to put it to the cluster

**Comment by marcinwadon** [comment]
@TheMMaciek Isn't it a duplicated ticket with the one you were working on?

**Comment by TheMMaciek** [comment]
Sounds exactly like #1174

**Comment by TheMMaciek** [comment]
Closing this one as #1174 is done.
