### ISSUE TITLE
CORS needed on AWS endpoints for web browser support

### ISSUE THREAD

**Issue by doc-holliday1** [Constellation-Labs/constellation#1055]
I'm getting this error when making requests to block-explorer:

`Access to XMLHttpRequest at 'https://3pii1fjixi.execute-api.us-west-1.amazonaws.com/cl-block-explorer-testnet/transactions/4307f4dc891580bb5874e114f669107e8121d17ac9846f081d25e7c4ae8e834b' from origin has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

**Comment by marcinwadon** [comment]
Done in block explorer v2
