### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [Constellation-Labs/constellation#1056]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by marcinwadon** [comment]
Hey @Neustradamus, we'll make it under #984

**Comment by Neustradamus** [comment]
@marcinwadon: Thanks but it is better to close this ticket after ^^

**Comment by Neustradamus** [comment]
@marcinwadon: Can you reopen, it is not solved.
