### ISSUE TITLE
Dead peer removal logic and restart handling

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#106]
Peer cleanup was temporarily disabled to debug other problems. Needs to be re-enabled and verify that it cannot accidentally remove live peers. Additionally we also need to pass more peer data during the handshake (which was turned off to enable clean testing.) On restart we need to add seed peers populated during deployment relative to the active cluster.

**Comment by buckysballs** [comment]
The cluster needs to automatically remove peers when they become unresponsive or misaligned so we can prevent forks and free up space for new peers to join. In the case that the cluster forks (misalignment amongst the top ranked peers), we need to restart the cluster and roll back to the most recent non-forked snapshot. In the case of an unresponsive or misaligned ordinary peer, the peer should be removed from the cluster.

In the case of a rollback, we should restart the cluster with the highest reputable peers (we will guarantee a fixed set of nodes at the highest reputation) and re-add the rest of the peers that are responsive to the restart flow.

Goal
1) A restart mechanism for forks amongst highest ranked peers (tip height misalignment).
2) A removal mechanism for peers that are misaligned or unresponsive.

Definition of Done:
1) Artificially induced misalignment amongst the highest ranked nodes causes a restart/rollback the the most recent aligned snapshot
2) Artificially induced misalignment amongst ordinary peers causes the peer to be removed from the cluster.

**Comment by wkoszycki** [comment]
connected with #603
