### ISSUE TITLE
Fix missing key from peer join in selfavoidingwalk

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#1118]

**Comment by marcinwadon** [comment]
cc: @buckysballs the hottest from mainnet:
![image.png](https://images.zenhubusercontent.com/57dd18bbe40e5714b16f064a/39cbfe72-0225-4b39-a280-09516a94b837)

**Comment by buckysballs** [comment]
Annoying, could u share more verbose logs over slack?
