### ISSUE TITLE
Verify run length encoding in Wallet/KeyUtils with BOLOS app and BIP44 implementation

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#1193]
We need to ensure that 

1) Our run length encoding is to the exact specifications here: https://github.com/Constellation-Labs/constellation/issues/735#issuecomment-619652684
2) Our BIP44 implementation https://github.com/Constellation-Labs/constellation/pull/1086 is compatible with the BOLOS app

**Comment by marcinwadon** [comment]
4 story points in Sprint 1
