### ISSUE TITLE
Transaction refs overwritten somewhere in the pipeline

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#1199]
We're seeing that Transactions returned from the block explorer have different previous Transaction refs than the origin al transaction. The client wallet sent with the correct prev refs are however verified. The main effect is a user cannot download their acct chain history. It's possible it could be a downstream processing error too (indexing to es)

Dod)
- Identify and fix overwriting of Transaction contents within the pipeline

**Comment by marcinwadon** [comment]
> The main effect is a user cannot download their acct chain history. It's possible it could be a downstream processing error too (indexing to es)
Actually it's not valid as the data from block explorer produces the same hashes as data sent to the cluster, so it means that the hash of transaction is insensitive for a last tx reference change. And that's definitely a bug @buckysballs

**Comment by kpudlik** [comment]
Let's make sure that block explorer uses latest jar. I will try to include release as sbt dependency
