### ISSUE TITLE
Add Alias to Node *feature enhancement*

### ISSUE THREAD

**Issue by ffox77** [Constellation-Labs/constellation#1204]
Having an Alias will offer a choice of using a more friendly name to reference a Node.

This provides a better visual identity of Nodes when navigating in D3 or seen in a monitoring tool.

It also makes it easier to ref in dialog i.e. "Jupiter is down" instead of "149.xx.xxx.xxx is down".

Some suggestions: a city name, planet, or the name of some celestial entity.

Possibly Impacted areas: whitelist file; endpoint _/cluster/info_ OR maybe it is something available directly on each Node as part of its _/metrics_

**Comment by marcinwadon** [comment]
It requires a change in the codebase as following:

- add alias/label/name entry in the whitelisting file (and csv reader)
- store that label in PeerData (if needed somewhere else) or just display that label in cluster/info endpoint directly from whitelisting map
