### ISSUE TITLE
Pull only consecutive transactions chain from pending transactions mempool

### ISSUE THREAD

**Issue by TheMMaciek** [Constellation-Labs/constellation#1241]
Currently we are only doing sanity checks on transactions for a given address in the pending mempool before pulling them for consensus e.i. checking if ordinals for pending transactions are greater or equal to last accepted transaction ordinal and if after sorting them by ordinal the first one correctly references the last accepted transaction.
We are not checking the relations between other transactions in pending and if they are referencing each other correctly hence creating the correct transaction chain. We should implement pulling only consecutive transactions chain by checking references to the last transaction (both hash and ordinal) between transactions in pending mempool and last accepted transaction for a given address.

connected to #1216

**Comment by marcinwadon** [comment]
1 story point in Sprint 1
