### ISSUE TITLE
Remove transactions stuck in pendingTrasactionsMemPool

### ISSUE THREAD

**Issue by TheMMaciek** [Constellation-Labs/constellation#1257]
Currently if transaction is incorrect e.g. it has correct ordinal but incorrect prevHash (it doesn't form a chain with other transactions) then it will get stuck in pending memPool. We should implement some logic that can clean transactions stuck in pending. We could implement lru cache with some timeout and also remove transactions while accepting checkpoint blocks - e.i. if transaction with certain ordinal is being accepted during checkpoint block acceptance than transactions with that or lower ordinal can be removed from pending.

Could you add more detail @buckysballs 

connected to #1216

**Comment by TheMMaciek** [comment]
We discussed with @marcinwadon and @kpudlik and we think that we shouldn't use timeout here, but handle all the cases and remove wrong transactions from pending.

**Comment by marcinwadon** [comment]
DoD:
- Remove transaction which cannot be accepted anymore (check if last ref is higher or lower than the transaction -> if higher, transaction cannot be accepted)
