### ISSUE TITLE
Use `{index}/_doc/{hash}` instead of search query to get things by hash in block explorer

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#1392]
We use search (term/match) request to get items by hash with depends on `refresh_interval` (so it is not real time).
We could switch to getting objects via `{index}/_doc/{hash}` to make it real time.

**Comment by kpudlik** [comment]
Already exists in Block Explorer V2

**Comment by marcinwadon** [comment]
https://github.com/Constellation-Labs/block_explorer/pull/41
