### ISSUE TITLE
Merkle implementation

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#142]
Should be tested independently of integration. There are some examples in other Scala / JVM crypto projects, see bitcoinj at least. (I think there's a better example though, citation needed)

**Comment by tynes** [comment]
What sort of merkle tree are you using? Similar to the bitcoin merkle tree? You should check out this: https://bitcointalk.org/?topic=102395

**Comment by ryle-goehausen** [comment]
Something similar to this: https://github.com/ACINQ/bitcoin-lib/blob/master/src/main/scala/fr/acinq/bitcoin/MerkleTree.scala but needs to be adapted to our schema. We won't allow duplicate transaction hashes in the DAG.

We'll add more info in whitepaper but a tldr; Merkle abstraction is just intended to be used on any topologically sorted quantity for optimizing data transfer and validation. This can be defined at the lowest level of any tip edge as well as the transaction data dependencies. Any ordered graph can have Merkle roots defined over any part of it, and they are a derived quantity from the raw chain data. They only need to be used in places where optimizing data transfer is appropriate, or in binary agreement during consensus or in obvious places on large snapshots. (i.e. not every edge necessarily requires a merkle root constructed over it, but it is always a definable quantity) this is primarily used for downloading / data transfer, and binary agreement across partitions during checkpoint construction

**Comment by ryle-goehausen** [comment]
First pass implemented, not ideal though.
