### ISSUE TITLE
SPIKE: Splunk research.

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#1440]
We need to check if Splunk can help us with avoiding `grep`ping manually.

**Comment by tbekas** [comment]
Info from @LukaszKoral 

> Graylog is a similar tool to Datadog and seems to be providing several interesting functions. There are both open source and enterprise versions, while free open source version already has things like analytics and alerting. You can take a look at this here in case you would not be fully satisfied with Splunk:
https://www.graylog.org/
https://www.graylog.org/products/open-source-vs-enterprise 

Cloud service hosting Graylog: https://www.stackhero.io/en/services/graylog#pricing

**Comment by LukaszKoral** [comment]
still waiting for feedback from @buckysballs regarding the Graylog vs Splunk

**Comment by LukaszKoral** [comment]
decision on planning - Splunk Enterprise
