### ISSUE TITLE
Clarification of address prefixes

### ISSUE THREAD

**Issue by Nikolaj-K** [Constellation-Labs/constellation#145]
In the data-visualization repo, `src/components/App/App.test.js`, we have half a dozen hard-coded addresses prefixed by `0xDAG` and I don't know what's the source of those. 
Example in the json:
```haskell
signers: [
        "0xDAG6jScEJp1FnZtxM6JEDbctwcUADU6BYzhV8d3U",
        "0xDAG3FFi4xgHFHAWLGZyL4bPFCQhUkhjoTD4PsWhq",
```

The hash contains small and capital letters. There's the `keyHashToAddress` function in 
`src/main/scala/org/constellation/crypto/KeyUtils.scala` 
in the constellation repo but I can't find if that utility function is actively used right now. 

* What's the hash from the key? It appears after `DAG` follows a digit - is that always the case?
* ! If the hash is not actually displayed in hex, I'm very much against a prefix with a wrong type annotation. For parsers, they'll not survive the G and it's long and misleading. You could go with `0DAG` or `DAG` (works especially if the char after DAG is a digit but I'd rethink even DAG if that's not necessarily followed by a digit). I'm not sure how far the cryptography decision in the file are (seems under construction), but I'd refrain from a technically wrong annotation. 
* Does the name `keyHashToAddress` derive from somewhere? Can't find it on github in another project or on the BitcoinJ repo that's linked to.
* Were those utils used to generate the hashes for the visualization? Can you point out which util functions aren't actually interwoven in the code/necessary for compilation? Might help with audits.

**Comment by prestonparris** [comment]
Here is the code used to create the addresses: https://github.com/Constellation-Labs/constellation/blob/c55eb72bb1bda05c16cfd885029235ac68c1854a/src/main/scala/org/constellation/crypto/KeyUtils.scala#L275

It is being actively used, the example you pointed to was just the test mock for the visualization layer.

How it works is a script calls every 30 seconds to a node and grabs the data from the endpoint located here: https://github.com/Constellation-Labs/constellation/blob/master/src/main/scala/org/constellation/API.scala#L428

The result of that is cached into redis along side a geolocation lookup. The visualization repo hits an endpoint which just serves up those cached results.

There is a separate repo for the caching layer script that I will open up shortly just need to make a change for security concerns.

**Comment by Nikolaj-K** [comment]
@prestonparris Thanks for the replies. That's a long chain of statements in the API file haha. I'll come back to that once I understand the node class.

And yes, I did linked to this `keyHashToAddress` function myself above - but I didn't find how the hash itself is computed. I think I saw "SHA2 squared" somewhere, which they use for bitcoin. In any case, the output of that doesn't seem to be hex and so I'm concerned about using the 0x prefix. E.g. Ethereum indeed uses 0x and then follows an actual hex number and you won't find a character beyond "f" in the address.
Am I confused?

**Comment by tynes** [comment]
@Nikolaj-K a bit of info on the double hash - https://en.bitcoin.it/wiki/Hashcash#Double_Hash
Also here are prefix bytes bitcoin uses in its address generation, they differ on the type of transactions the address will be used for - https://github.com/satoshilabs/slips/blob/master/slip-0132.md

**Comment by Nikolaj-K** [comment]
@tynes What I wanted to get at is that you can't write `0x5g88jb1e` as `5g88jb1e` is not hex. That's a wrong type annotation. The first row in the link e.g. speak about the prefix xprv for 0x0488ade4, but they don't mix things up. In the testnet-visualizar and the `keyHashToAddress` function, Constellation currently prefixes the address (which isn't hex) with `0xDAG`. You can't, in any case, follow 0x by something that has a G in it. That's why I proposing at the very least dropping that `x`.

**Comment by prestonparris** [comment]
@Nikolaj-K just open sourced the dashboard server: https://github.com/Constellation-Labs/dashboard-server

I am unclear about your concerns around the 0x exactly, @ryle-goehausen  might have an opinion on this since he was the one that created the address code initially.

**Comment by tynes** [comment]
@prestonparris `0x` generally means that the following characters are to be interpreted as hexadecimal. The normal character set for hexadecimal is `[0-9a-f]`

https://en.wikipedia.org/wiki/Hexadecimal

`It uses sixteen distinct symbols, most often the
symbols 0–9 to represent values zero to nine, and
A–F (or alternatively a–f) to represent values ten to fifteen.`

By including a `G`, which is outside of the hexadecimal character set, it breaks developer assumptions which leads to a bad time

**Comment by Nikolaj-K** [comment]
What tynes say, but it's not just the G in DAG. The examples I give in the opening post make it clear that the hash used also doesn't output a hex number

```haskell
signers: [
        "0xDAG6jScEJp1FnZtxM6JEDbctwcUADU6BYzhV8d3U",
        "0xDAG3FFi4xgHFHAWLGZyL4bPFCQhUkhjoTD4PsWhq",
```

Compare this with the following Ethereum number I picked from the front page of Etherscan:

https://etherscan.io/address/0x40966ddf61213b096ae84d2e2c7ad349fdfe275e

The address here
`0x40966ddf61213b096ae84d2e2c7ad349fdfe275e`
is an integer. Googing the next best hex converter, I find that this Ethereum address is the integer

368730092363747367054088213623083770946397284190

Meanwhile, the string

`0xDAG6jScEJp1FnZtxM6JEDbctwcUADU6BYzhV8d3U`

from the example above presents itself as a hex number but clearly isn't.

**Comment by tynes** [comment]
I'm guessing the addresses are actually base58 check encoding?

**Comment by ryle-goehausen** [comment]
Fixed here: https://github.com/Constellation-Labs/constellation/pull/151 thanks @Nikolaj-K
