### ISSUE TITLE
When alias is wrong in dag reset CLI, no error given, NullPointerException in logs

### ISSUE THREAD

**Issue by ncoronges** [Constellation-Labs/constellation#1583]
When we got our node up and running we were initially using the wrong alias . The dag reset process completed and the only error we got was "port 9002 unresponsive". In app.log it shows NullPointerException in KeyStorageUtils:209. Had to do some digging to figure out what was wrong. 
Be nice to throw an exception and describe error in dag reset CLI. 
```
[36mo.c.ConstellationNode$[0;39m - An error occurred during startup process. 
java.lang.NullPointerException: null
	at org.constellation.keytool.KeyStoreUtils$.$anonfun$unlockKeyPair$1(KeyStoreUtils.scala:209)
```

**Comment by marcinwadon** [comment]
Hey @ncoronges. To unlock your keystore, you have to provide the same alias you used for creating the private key (and better keep it private) :)

For the node alias (aka nickname) you can use whatever name you want but it's stored in the whitelisting file right now, so it can be changed only by the CL team.
