### ISSUE TITLE
Validation JSON schema examples

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#172]
For dApp support we need to make simple examples for JSON schema required to implement simple application. Simplest example would be a user wanting to execute a proof of work operation as a service (which would act as a custom validation rule,) including all requests involved in verifying the execution operation.

Also need to discuss what other state transitions (besides +- on address ledger space,) we'll allow as pure JSON (independent of external custom validation execution,) such as consensus on hash values and agreement on address updates (i.e. preserving a latest hash value on a chain representing data off-chain.)

https://developer.holochain.org/Validation_Functions

**Comment by Nikolaj-K** [comment]
@ryle-goehausen I'm designing a decentralized ranking ranking system for the "dApp store" aspect of a dApp client product that a friend is currently doing an ICO for
https://github.com/nos
He has a following of 100++ active smart contract devs, e.g. see competitons like that
https://medium.com/nos-io/nos-design-competition-results-introducing-the-nos-portal-6e5e690a951e
in this space or so and interested in a conversation. He sites exactly at that end of the problem. 
I can set up a conversation where we could share experiences/requirements, in case I'd be able to use the constellation protocol. 

I had mentioned this to @tylerprete in the discord at one point (btw. tyler, I made some notes on the docs vs. wiki relation there some time ago.)
