### ISSUE TITLE
Trust influence mockup

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#173]
Adapt existing REST endpoints for node assigned trust scores to verify integrity. Should query all peers to find their public scores to other nodes and build node trust graph. Later will influence node rebalancing and topology, for now just use for consensus score determinations during voting / conflict resolution. Eventually will also be committed on-chain similar to join/leave logic for reputation calculations. Should also be consistent with Algebird summations

**Comment by marcinwadon** [comment]
@buckysballs is it still relevant or can we close it?
