### ISSUE TITLE
Graph validation. Ancestry self-consistency and tips mergeable function

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#223]
Our current validation function is here: https://github.com/Constellation-Labs/constellation/blob/696e6d6ee6ad30fe9e41b2d2d78bb0b52bb35bd5/src/main/scala/org/constellation/primitives/Schema.scala#L466

This isn’t sufficient for a DAG, it’s a placeholder for a more proper validation function. It just checks the current ledger state to see if all transactions in a CB are valid. That state is relative to all transactions the node has currently accepted, but doesn't reflect the internal self-consistency of the ancestors of that CB.

Blocks need to be validated with respect to the diff of their ancestors since the last snapshot. Each block contains a group of transactions, and each contains parent references. The parent references since the last snapshot should all be taken as a single group, and their transactions merged into a single 'diff map' of address -> diff of balance. 

To find the ancestors since the last snapshot, they're stored in the tip service here as 'acceptedCBSinceSnapshot': https://github.com/Constellation-Labs/constellation/blob/392fd8bc81ed434fce8af812de05d375d7d0d6f9/src/main/scala/org/constellation/primitives/EdgeDAO.scala#L64

The current snapshot is also stored there: https://github.com/Constellation-Labs/constellation/blob/392fd8bc81ed434fce8af812de05d375d7d0d6f9/src/main/scala/org/constellation/primitives/EdgeDAO.scala#L66

But right now the ledger is only being updated for the N-1 snapshot: https://github.com/Constellation-Labs/constellation/blob/41f9c3e3294ec3ff29eff83a65b2eb886492398a/src/main/scala/org/constellation/consensus/EdgeProcessor.scala#L482 (so the diff should be maintained for the blocks in the current snapshot ++ the acceptedCBSinceSnapshot)

Validation can be tested independently of the main E2E test since it's relatively simple.

There's a graph generation unit test here:
https://github.com/Constellation-Labs/constellation/blob/41f9c3e3294ec3ff29eff83a65b2eb886492398a/src/test/scala/org/constellation/consensus/RandomDataTest.scala#L63

Needs to be modified to make a pseudo-snapshot. (Should just make a snapshot of all new blocks every 10 blocks or so, something simple.)

From this, validation should be tested by maintaining a ledger from the last snapshot, and a diff for all keys affected by each block including all ancestors since the last snapshot. Each block should maintain a diff map and when creating a new one, the diff should be validated to not contain a double spend within its own ancestors. (I.e, the should be no diff that lowers the previous ledger state below zero.) There should be no duplicate hashes for CB's or transactions in the ancestors. There will be a separate process for checking for duplicates in the old snapshot history, this ticket should only be concerned with checking for hash duplicates in CBs / transaction hashes for ancestors up to the snapshot.

Tests should include invalidation conditions, i.e. trivial ones such as a double spend. But also the case where 2 sections of the graph create a valid condition but are internally inconsistent (i.e. two separate blocks with no common ancestors whose sum balance is valid, but which are each internally invalid when not incorporating each other.)

For comparison, see IOTA's implementation here: https://github.com/iotaledger/iri/blob/00b75745b9e0af07c90af6f8ac56ca7c2962089c/src/main/java/com/iota/iri/LedgerValidator.java#L269

**Comment by marcinwadon** [comment]
#246

**Comment by marcinwadon** [comment]
@ryle-goehausen I think we're good to close the issue as the #246 has been merged.
