### ISSUE TITLE
Fix issues with multiple main methods interfering with docker run command

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#227]
We have several mains in the integration test folder that cause an issue when put into the src/main folder. Docker should have the main class for node runner specified, but when we package a second main method into the regular classpath it breaks the docker image run command and node doesn't come online properly. 

Need to investigate and fix so we can put more utility methods in the main class instead of relying on src/it folder.

**Comment by Nikolaj-K** [comment]
I work with folks who full-time work on the private-net setup and container-magic of bigger protocol projects out there - let me know if you happen to need info or reference experience in terms of dockerization for nodes deployment and such.

**Comment by nunojusto** [comment]
Hi, do you use plain Dockerfile or any other sdk docker build?
Where can i see info how you are building the image?

**Comment by ryle-goehausen** [comment]
@nunojusto We're using the sbt docker plugin: https://www.scala-sbt.org/sbt-native-packager/formats/docker.html

**Comment by marcinwadon** [comment]
@Nikolaj-K When I was trying to launch it under `10.0.1` I had the same issue :) Then I switched to the version `1.8` and it works correctly.

**Comment by Nikolaj-K** [comment]
@marcinwadon Ah, good to know. Are you on discord to report back to that guy on the #dev-general channel?

**Comment by marcinwadon** [comment]
@Nikolaj-K No, I'm not on discord

**Comment by Nikolaj-K** [comment]
@marcinwadon It's only the about 10 to-be node operator people in that chat and right now only asking about things when people are lost, but it's probably still worth joining to see what issues are first hand. One needs some communication for such discussion channel if one wants to avoid extended communication e.g. here in tickets. Are you on Slack (in general I mean)? It might be worth moving the Constellation communication that's not the traders to that medium - now that the discord is tiny - or consider other more dev friendly options for chats.
