### ISSUE TITLE
Re-enable CI/CD on dev branch for dev cluster

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#234]
Currently disabled after testing on compute vs kube. Should have a 5~ node persistent dev cluster that should be redeployed on changes to dev. This is pretty trivial now, can just use the deploy script for building a new jar. Might need to clone terraform scripts for a permanent dev cluster configuration.

**Comment by tylerprete** [comment]
Also -- Circle says the 1.0 configuration is deprecated and no longer supported. We should port our config to version 2.0.

**Comment by ryle-goehausen** [comment]
There's a full-deploy.sh script which might help with this now.
