### ISSUE TITLE
Update integration test to cover download process

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#238]
Should also poll nodes to verify alignment / integrity. Alignment in the sense of snapshot agreement among nodes, and requesting recent data to verify snapshot data is correct.

**Comment by ryle-goehausen** [comment]
See example in E2E process.

**Comment by buckysballs** [comment]
And re-download. 

DoD)
1) reDownload test in IT tests
2) reDownload in e2e
3) Download/join in ClusterTest 
4) Download/join in e2e

**Comment by marcinwadon** [comment]
@buckysballs Integration test is described under #790. If you want to, please add next scenarios there
