### ISSUE TITLE
Grafana* dashboard for metrics

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#240]
Should embed into node UI and run alongside. Needs to be added to deploy / startup scripts and ideally clear stored data upon restart of service. 

Should also add JVM metrics to it.

**Comment by digitaltwinnn** [comment]
I would like to create a PR shortly for a working example which I have running on my local machine. 

It is using the micrometer-akka library to collect JVM metrics and Akka metrics. It can export in a prometheus format a.o., so i'll have a look at Grafana now to create a neat dashboard as there are already some existing micrometer templates. I think Kibana nowadays is only tied to elasticsearch

**Comment by ryle-goehausen** [comment]
@tylerprete has implemented parts of this but not fully automated yet.
