### ISSUE TITLE
[ERROR] Failed to construct terminal

### ISSUE THREAD

**Issue by ByteFan** [Constellation-Labs/constellation#244]
When running build.sh

"[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"

Running on Ubuntu 18.04.1 LTS

openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode

Looks like : https://github.com/lihaoyi/mill/issues/139

**Comment by ryle-goehausen** [comment]
Upgraded sbt version should fix this now.
