### ISSUE TITLE
Complete peer lookup on PeerAPI

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#276]
There's partial implementation of extractClientIP but in general all the endpoints should be wrapped in a lookup that resolves the IP to an Id

**Comment by ryle-goehausen** [comment]
This is a requirement for security. We currently have updates happening that don't validate the originating IP as belonging to an ID, hence anyone can spoof those.

**Comment by ryle-goehausen** [comment]
https://stackoverflow.com/questions/40132262/obtaining-the-client-ip-in-akka-http

See here, extractClientIP just uses headers, so we need solution here ^ to solve actual problem.

**Comment by ThomasvandenBroek** [comment]
Estimate: 2 days
