### ISSUE TITLE
Join/Leave process

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#283]
Nodes need to be able to broadcast to peers and notarize on chain their intention to leave the network. This is for enforcing penalties/assigning rewards based on behavior and so that the network can repartition itself according to shuffling of nodes. Ideally there should be a transaction/message type for nodes to signal that they are going offline, extending the transaction/message, class adding an optional field for metadata, and being signed by the node sending the join/leave request.

**Comment by ryle-goehausen** [comment]
For now, to maintain compatibility with partitioning, the most expedient thing to do is to add this as a field on the checkpoint data (similar to channel message) indicating a node id that is joining / leaving.
