### ISSUE TITLE
Separate transaction validation for mempool addition

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#287]
Checkpoint validation is already implemented but there are a few criteria we can use to pre-filter transactions. The presence of a hash duplicate in previous snapshots is partially implemented as a Sway persistent set. The hash duplicate of a recent transaction should also be implemented. When nodes are receiving transactions gossiped from other peers (not part of a block formation) they should immediately attempt to perform a simple validation of them. 

https://github.com/Constellation-Labs/constellation/blob/c58f84cf1fae878f6b8c419d95e14e768917528e/src/main/scala/org/constellation/primitives/Transaction.scala#L81 

The other criteria used for prefiltering should also be to validate it against the current snapshot balance, and a few randomly chosen tips. This won't exclude the transaction necessarily if it's invalid, but will deprioritize it.

**Comment by marcinwadon** [comment]
@buckysballs This issue isn't finished. Pull request #329 was only a base to be able to add new validators for TXs similar to those which are for CheckpointBlock.

**Comment by buckysballs** [comment]
Thanks @marcinwadon !

**Comment by ThomasvandenBroek** [comment]
Estimate: 2 days

**Comment by marcinwadon** [comment]
Waiting for #347 to be finished
