### ISSUE TITLE
Add timestamps to blocks

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#288]
Self-explanatory, validation criteria should be whether timestamp is within some threshold window.

**Comment by Nikolaj-K** [comment]
Is this System.currentTimeMillis()? 
That's the common one I saw, although there are a few instances of nano times. Is that always just benchmarks or what's actually the rule when one has to go down?
(Some time differences in the system are also expressed in seconds)

**Comment by ryle-goehausen** [comment]
Yes. It seems meaningless to use nanoTime when theres a large window allowed for validation. 

I think we should be ok re: hashes. There's a salt added to transactions to guard against same amount / sender / receiver yielding same hash, we could add an explicit ID or a timestamp or something else but it's fine for now. Since a TX hash can only uniquely belong to one block it should be impossible to create a duplicate block hash.

**Comment by Nikolaj-K** [comment]
@ryle-goehausen Ah, yeah I was just talking about an identifier of the block.

When you talk about transactions, then I don't know what mechanism to prevent [replay attacks](https://en.wikipedia.org/wiki/Replay_attack) of raw transactions (across the DAG without UTXO ) you have in place. 
If the salt is controlled by someone, so there's no way around an explicit comparison check either way as far as I see.
