### ISSUE TITLE
Resolver mechanism and storage

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#296]
Resolution is partially implemented for transactions, but hasn't been enabled yet, see #201 for ticket to enable it. There is resolving occurring on FinishedCheckpoint and during consensus but it's not very smart. 

Data resolution should download data from other nodes in general (blocks or transactions) and store them. Blocks should only resolve up to a maximum depth parameter (i.e. don't infinitely scroll back,) or a maximum total timeout / retries. 

Upon completion of resolution (i.e. connecting to known data), nodes will have sufficient data to perform ancestry validation. They should only attempt to use resolved data for tips if it has not already been used as a tip (which must be tracked in a block store elsewhere.) They should also check for conflicts with existing tips but that requires #295

**Comment by ThomasvandenBroek** [comment]
Estimate: 0.5 day

**Comment by wkoszycki** [comment]
https://github.com/Constellation-Labs/constellation/pull/381
