### ISSUE TITLE
Update send transaction in UI to use XHR post to "send" instead of form to "submitTX"

### ISSUE THREAD

**Issue by tylerprete** [Constellation-Labs/constellation#307]
https://github.com/Constellation-Labs/constellation/blob/dev/ui/src/main/scala/org/constellation/ui/App.scala#L138

Currently posts as formData to "submitTX" endpoint that was removed.

Should use json with XHR post to "send" endpoint.

Look at impl for channels for correct pattern:
https://github.com/Constellation-Labs/constellation/blob/dev/ui/src/main/scala/org/constellation/ui/App.scala#L325

**Comment by tylerprete** [comment]
https://github.com/Constellation-Labs/constellation/blob/dev/ui/src/main/scala/org/constellation/ui/App.scala#L138

Currently posts as formData to an endpoint that was removed.

Should use json with XHR post to "send" endpoint.

**Comment by marcinwadon** [comment]
Closing as it's an outdated issue. It's related to the UI which we no longer use
