### ISSUE TITLE
Isolation of validation logic when snapshot is updating the ledger

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#338]
When the snapshot updates the ledger, it causes an issue where transactions / blocks being validated / consensus running in the background could read balances from 2 different snapshots causing a failure.

There needs to be a lock around the snapshot updating the ledger so that it's guaranteed when running validation that the correct ledger amounts are being read.

**Comment by ThomasvandenBroek** [comment]
Estimate: 3 days
