### ISSUE TITLE
Update consensus to include final agreement step on set of signatures associated with majority block

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#344]
After the nodes merge the signatures from the majority baseHash (the hash being signed,) they also need to agree on the majority final collection of signatures before acceptance. Basically same process as resolveMajorityCheckpointBlock but this time on the soeHash

**Comment by marcinwadon** [comment]
Right now during the consensus nodes don't agree on the majority final collection of signatures. Each node just receives CheckpointBlock proposals, then groups them by `baseHash` and takes the one which has most occurrences. Should it be changed to just group by both `baseHash` and `soeHash`?

**Comment by ThomasvandenBroek** [comment]
Estimate: 2days

**Comment by marcinwadon** [comment]
Just to keep it written down somewhere - basically there should be another step in the crosstalk consensus just before accepting final checkpoint block. Each node should broadcast to other facilitators which checkpoint block they will choose and if any node would like to choose other than most common one, it should change the decision and choose the most commonly chosen one.
