### ISSUE TITLE
Conflict storage requirements

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#348]
Right now CBs are stored under baseHash (not soeHash). There needs to be storage around conflicts such that a given baseHash could map to potentially multiple blocks, with one considered the 'primary' accepted at any given point. 

SoeHash will always uniquely point to one block, but may have children that are potentially in conflict. There should be a set of primary children that are considered currently accepted by the node, as well as other potentially conflicting children.

**Comment by ThomasvandenBroek** [comment]
Estimate: 3 days
