### ISSUE TITLE
Tip conflict management

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#349]
When a conflicting tip is observed, it needs to be stored (and there needs to be a function to determine if two tips are conflicting.) The active tips for a node should have no conflicts between them, and a node should not attempt to use a tip which conflicts with the active set, but still needs to store it (up to the snapshot, where conflicting values are pruned.)

#329 started adding transaction validation, but we need an arbitrary function for validating transactions against active tips still as well (which is related to this,)

**Comment by ThomasvandenBroek** [comment]
To be verified

**Comment by wkoszycki** [comment]
might be covered by #295

**Comment by wkoszycki** [comment]
This was already covered by implementing #295 and PR https://github.com/Constellation-Labs/constellation/pull/373/ 

However somehow this PR was not merged and closed (accidentally? ) so rebasing against dev fixing conflicts and review needs to be done anyway thus ~ 2-4h of work

**Comment by wkoszycki** [comment]
>When a conflicting tip is observed, it needs to be stored (and there needs to be a function to determine if two tips are conflicting.) 

Conflicting tips are stored in TipService

>The active tips for a node should have no conflicts between them, 

Covered

>node should not attempt to use a tip which conflicts with the active set

Covered  by previous one

>but still needs to store it (up to the snapshot, where conflicting values are pruned.)

Values are not pruned on snapshot

So the question is why do wee need to store conflicting blocks  ? We are not doing anything with them for  now (even pruning ) . I am asking in terms of other issue that came out  if there is a conflict we return conflicting transaction back to pending which then causes further conflicts. To summarize if accept is called and block is in conflict with already accepted block should we choose (based upon reputation etc.) to choose one of them ? If yes that will be difficult to revert it in scenario when already accepted block would be used as tip somewhere.

**Comment by buckysballs** [comment]
The original idea was to store these for use in the reputation model but we can just store an Experience in the reputation service for now that a conflicting block was proposed. If a node proposes a conflicting block right now it means it hasn’t received the already accepted block so we should accept the first and move transactions that have not been accepted back into pending. If a transaction in the conflicting block has already been accepted we should not store it in pending and remove from pending if it is in there
