### ISSUE TITLE
Integrate reputation model into conflict handling/snapshot misalignment

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#376]
We need keep track of the reputation (eigentrust) scores across peers, such that they update with the receipt of new transactions/checkpoint blocks, and finalize with the formation of a snapshot. We can achieve this by adding an in memory data store that stores the reputation of peers and is updates during resolution #359. 

This will be used in both validator rewards and rate limiting. In terms of rate limiting, given the most recent snapshot, we will uses the reputation scores for each peer in the snapshot to determine the amount of transactions that a it can submit in the next snapshot. More on this in #375 

For now, let's use the EigenTrust model in alpha-testbed (https://github.com/djelenc/alpha-testbed/blob/master/src/main/java/atb/trustmodel/EigenTrust.java). When we receive new information from a peer, we denote a positive observation as the proposal (#335 ) of a transaction/checkpoint block that has been sent from the correct (as denoted by XOR distance) peer that is valid, and negative if it is invalid. In the case that we receive a proposal from the proceeding peer, we should denote that as a positive observation from this peer and a negative observation for all preceding peers. In the case where a peer proposes a 

The end result is to use reputation in the case of conflicts, where if we receive conflicting information from two peers we choose the information from the peer with the highest reputation.

In terms of features for determining positive and negative observations, we need to incorporate rate handling, correct gossip routing and timeouts. 

Successful criteria requires completion of rate limiting and modifications to limits based on optional tx fees.

**Comment by Nikolaj-K** [comment]
Sidenote: It could be worth strategizing over how to embed/link against copylefted code, or how to license ones own repo.

**Comment by buckysballs** [comment]
3 days

**Comment by buckysballs** [comment]
We need to keep track of observations of successful/unsuccessful actions each node performs, adding +1/-1 for each positive or negative action. This forms the feature space for Eigentrust to operate on. This can be managed as follows:
1) Create a service that holds a reputation matrix from the previous snapshot.
2) After implementation of #228, add metadata to Transaction on the 'route' of the transaction as it is gossipped to peers
3) Upon the creation of snapshots we can recurse through its contents and filling up a new matrix for the reputation service out of metadata on the performance of each node stored in the snapshot. Nodes that drop or miss transactions (they should have received/signed via the gossip model) get a -1. Nodes that sign or propose invalid transactions should get -1. A +1 for otherwise.
4) Make this matrix available to the reputation service which can then output a reputation matrix.

**Comment by buckysballs** [comment]
Note: Let's only use the rep model for accepting snapshots. In the case of conflicting or invalid or missing block proposals, we should treat those as Experiences to be aggregated by the reputation service.
