### ISSUE TITLE
Rate limiting and management in case of transaction fee

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#384]
An entity who deploys a peer in the network will want the ability to submit transactions freely. Since, we will have a fixed maximum transaction rate (transactions per second) the amount of acceptable transactions should be proportional to the peer's success as a facilitator. This can be done by rate limiting peers according to a metric of success, which we will be calculating as a subprocess give us reputation scores (#376).

We should choose to reward peers at the creation of a snapshot because there is unanimous agreement across peers. Based on a configuration of the maximum transactions possible (we can hard code for now), we need to determine a 'proportion' of the total maximum that a peer is allotted within the snapshot window. This can be mocked for now using a RateHandler.validatorRateAllowance on branch rate-limit.

If the peer wishes to go outside of that window, then transactions which pay a fee can be admitted, but would de-prioritize transactions from the total transactions possible. Transaction should be sorted in importance by whether a fee is paid and the size of the optional fee. The optional fee should be added to the total rewards for the snapshot (contained in Rewards) and distributed amongst the facilitators according to their current reputation/trust score for the round. 

For transactions coming from offline accounts, allow them one free transaction per snapshot. A configurable percentage of the total amount of transactions per snapshot should be reserved for offline accounts and any 'offline' transactions beyond this should be queued for the next snapshot, but prioritized by an optional transaction fee. The queue should be fixed and drop transactions when full.

Goals:
1) We need to change to the Transaction data type to support an optional fee parameter (Option[Double]).
2) We need to way to configure the total transactions per snapshot and a percentage reserved for offline accounts. This can be hard coded for now.
3) We need a service to keep track of transactions submitted per account, which should probably be a part of the peerAPI service, and prevent transactions which are outside the submitting account's allowance from being added to the tx mempool.
4) This service needs to communicate with a reputation service to get the matrix of reputation scores which will be used in calculating. This can be mocked if completed before(#376)

Definition of Done:
1) Transaction has an optional fee parameter
2) A maximum number of transactions per snapshot is enforced and transactions beyond this amount are dropped.
3) Accounts can only submit their allowed amount of transactions and any transactions submitted beyond this amount are dropped.
4) Accounts can submit transactions with a fee, effectively reducing the allowance of all peers but increasing the rewards for the snapshot.

**Comment by buckysballs** [comment]
I wanted to make a small adjustment. To this criteria

```Transaction should be sorted in importance by whether a fee is paid and the size of the optional fee.``` It's going to be difficult to sort fees such that the highest are guaranteed to end up in checkpoint blocks first. Let's just sort transactions pulled from the mempool by their fee provided, but know that the fee's ability to ensure priority will be probabilistic.

**Comment by wkoszycki** [comment]
Please note that this condition

> A maximum number of transactions per snapshot is enforced and transactions beyond this amount are dropped.
is not satisfied by #486 thus this issue shouldn't be close even when merging that branch
