### ISSUE TITLE
Feature engineering for a Meme

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#4]
We need to figure out what features give us the best signal regarding node honesty while also minimizing computational overhead. I'm going to propose a simple heuristic initially but I would like to follow in the footsteps of REGRET. To clarify from here on out, a meme will represent the feature space of some reputation model.

With regards to computational overhead, we need to be cognizant of how memes are used. See issue #7 for a details, to which this will be heavily tied. This encompasses the data science portion of the efforts which will most likely require dimensionality reduction via PCA or something similar.

**Comment by ryle-goehausen** [comment]
This is too much for one ticket, need to split up and revisit elsewhere. Closing for now. Will re-open more tickets later related to each section.
