### ISSUE TITLE
Offline node for a desktop wallet app

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#400]
We need to have a basic wallet app for sending transactions to the validating peers. To start, we can modify the ConstellationApp to start in an 'offline mode', allowing for transactions to be sent via the current ui. We also need to add a mechanism for peer finding a peer to send transactions too. This could be a standalone server that would function as a block explorer in the future.

**Comment by Nikolaj-K** [comment]
I propose to write the tool for broadcasting raw transactions and wrap the wallet (making use of keys) around it - so that people can also create transactions offline. Makes the tool much safer for early version use.
