### ISSUE TITLE
optimize getTransactionsTillSnapshot and isConflictingWithOthers

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#419]
The app needs to remove expensive validation checks and lookups in order to maintain performance. Based on testing last week, getTransactionsTillSnapshot is using increasing amounts of CPU and isConflictingWithOthers takes exponentially longer to complete with respect to the number of checkpoint blocks checked for conflicts. We should

1) Optimize these functions locally with comprehensive unit tests.
2) Ensure that optimized implementation of these functions maintain performance during long running cluster tests.

**Comment by marcinwadon** [comment]
@wkoszycki Just want to add that the problem is not necessary in those functions but can be in functions which are used inside (i.e. converting from merkle multiplied by amount of data to process)
