### ISSUE TITLE
Missing checkpoint block validation by facilitators during consensus

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#420]
We need to add a validation step to validate checkpoint blocks received from peers when a node is acting as a facilitator. This can be tested locally. Success criteria:

1) Add validation step within consensus when a checkpoint block is received by a facilitator
2) Add unit tests for error handling. If there is consensus around an invalid checkpoint block a node should assume that it is missing information and trigger a download/restart as described in #106

**Comment by wkoszycki** [comment]
Validation function relies on `isInSnapshot` which is checking `acceptedCbSinceSnapshot` collection. How about scenario when parents wasn't accepted yet ? you would then assume that there are in snapshot but they are not. We shouldn't traverse the whole bunch of snapshot so it's not clear how to resolve it.

**Comment by buckysballs** [comment]
Good point. Checkpoints should not be proposed without their parents having been accepted by at least some peers and the peer proposing should definitely have them. So we should first check recently accepted cbs, and if the parents are not found, resolve the parents from the peer proposing the checkpoint block. If a cascading issue of missing parents happens, (continuously resolving and no parent in recent cbs) we will want to throw an exception and cancel this consensus round. Also, once we have a reputation service, we will want to add an 'observation' that the offending node proposed checkpoints with missing parents.
