### ISSUE TITLE
Consensus stages should move forward only

### ISSUE THREAD

**Issue by wkoszycki** [Constellation-Labs/constellation#457]
In current implementation one node can run same stage multiple time for example `transaction proposals` this happen when timeout occurs and after that timeout missing transaction proposal is received then the condition for all proposals is satisfied and node performs same action twice.

To overcome this issue we could use either `context.become` or `akka fsm actor`.

This fix need to apply for all stages so that following methods can be called **at most once**:
- `unionProposals`
- `acceptMajorityCheckpointBlock`
- `resolveMajorityCheckpointBlock`

**Comment by buckysballs** [comment]
Let's see if it's possible to implement without a big refactor.
