### ISSUE TITLE
Snapshot creation increasing in time and memory - SOE lookups preventing eviction from SOEService cache

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#458]
We've identified that snapshot is taking increasingly longer and corresponding to memory spikes. This also aligns with fact that during snapshot creation, the SOE service is not evicting according to its eviction policy of 4hrs after access, indicating that snapshot creation is accessing the SOE service in a potentially o(n) operation. Here are some snapshots from the metrics board as evidence.

![image (1)](https://user-images.githubusercontent.com/4953237/59123720-ce981200-8912-11e9-8852-44ae5a8cd020.png)
![image](https://user-images.githubusercontent.com/4953237/59123769-e66f9600-8912-11e9-8bed-b080a0b6723d.png)

**Comment by marcinwadon** [comment]
Reopened because the issue isn't fixed properly
