### ISSUE TITLE
Turn on stackdriver logging with retention policy

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#467]
Need to re-enable GCP stackdriver logging with a short retention policy and enable on test environment so we have searchable logs. Retention policy of ~5 days should be enough to start with.

**Comment by wkoszycki** [comment]
@buckysballs please clarify if we need migration for elk/grafana stackdriver monitoring

**Comment by marcinwadon** [comment]
Closing because we're using kibana monitoring
