### ISSUE TITLE
Cluster size testing - ensuring cluster stability 60 nodes

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#501]
We need to determine the maximum cluster size our current implementation can handle. To do so, we need to test increasingly larger cluster sizes and ensure that under the load testing (to be implemented in #497) that the cluster stays in sync and does not undergo memory issues.

Success criteria are

1) Deploy a cluster of size 12, 24, 48, 96 and have them undergo load testing 

Note: Once the reputation process is implemented, we should redeploy a cluster with the max size and configuration that we discover, and ensure memory safety and synchronization.

**Comment by wkoszycki** [comment]
Let's keep this ticket for 60 nodes cluster and create a separate one for 96
