### ISSUE TITLE
Optimize memory usage and add protections to in memory data stores

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#502]
Before we deploy Main Net and move on to other milestones, we need to audit our node "pipeline" to ensure that our in memory data stores are optimized and that all accessor methods are protected for concurrency. This is a large scoped ticket which requires:

1) Audit of all datastores, accessor methods and migrations in an organized in a document
2) Addition of protections to all data stores
3) Optimization of in memory stores - size, timed expiration, etc.

Note: We should complete #501 and ensure that memory is stable at our max cluster size. Acceptance criteria would be 12-24hr test with stabilized memory on Graffana

**Comment by wkoszycki** [comment]
Data protections for concurrency has been added.
