### ISSUE TITLE
Join/Leave testing across GCP accounts

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#554]
We've successfully completed and tested the Join/Leave process #487. Now, we need to test a node joining and leaving from outside the GCP account of an existing cluster. In order to test this we need to

1) Create a new GCP account within a free tier, which should have enough free credits to deploy one node
2) Successfully replicate the joining/leaving process tested in #487, with the joining/leaving node deployed on the new GCP account.

Considerations: 
We may have to register a Service Account on our main GCP account to allow the node on the new account to access the existing cluster.

DoD: A node deployed on a new GCP account can successfully join/leave a cluster deployed on our main account.

**Comment by marcinwadon** [comment]
I've successfully tested the join/leave process with 3 nodes on the GCP and 4th node connected from AWS
