### ISSUE TITLE
Select cluster majority state based on common snapshot hash/height instead last one

### ISSUE THREAD

**Issue by wkoszycki** [Constellation-Labs/constellation#561]
Re download logic is triggered whenever nodes snapshots are misaligned (different hash on same height) or below cluster (current height + configured interval is lower than majority cluster height ) 

Currently majority state is elected by grouping recent snapshots lists, it's often leads to choose lower bounded nodes to be chosen so in following scenario: 

```
+    it("should return snapshots to download till common majority hash and elect leader") {
+      val node1 = Id("node1") -> List(
+        RecentSnapshot("foo", 8),
+        RecentSnapshot("6", 6),
+        RecentSnapshot("4", 4),
+        RecentSnapshot("2", 2),
+        RecentSnapshot("0", 0)
+      )
+      val node2 = Id("node2") -> List(
+        RecentSnapshot("bar", 8),
+        RecentSnapshot("6", 6),
+        RecentSnapshot("4", 4),
+        RecentSnapshot("2", 2),
+        RecentSnapshot("0", 0)
+      )
+      val node3 = Id("node3") -> List(
+        RecentSnapshot("baz", 8),
+        RecentSnapshot("6", 6),
+        RecentSnapshot("4", 4),
+        RecentSnapshot("2", 2),
+        RecentSnapshot("0", 0)
+      )
+      val node4 = Id("node2") -> List(RecentSnapshot("2", 2), RecentSnapshot("0", 0))
+      val node5 = Id("node2") -> List(RecentSnapshot("2", 2), RecentSnapshot("0", 0))
+      val state = List(node1, node2, node3, node4, node5)
+      val ids = List(Id("node1"), Id("node2"))
+
+      val ownSnapshots = List(2, 0).map(i => RecentSnapshot(s"$i", i))
+
+      compareSnapshotState(ownSnapshots, state) shouldBe SnapshotDiff(
+        List(),
+        List(RecentSnapshot("bar", 8), RecentSnapshot("6", 6), RecentSnapshot("4", 4)),
+        List(node2._1)
+      )
+    }
```
last matching Snapshot (> 51% required) is `RecentSnapshot("6", 6)` and should be treated as reference state if it will turns out that the re-download must happen then leader should be elected based upon Id sorting (in future it will be swapped to reputation service)

**Comment by wkoszycki** [comment]
@mchrapek please also notice that currently we are not including self state to calculate cluster state it's a mistake we should definitely do that

**Comment by mchrapek** [comment]
Info @buckysballs : 
We need to store the height of the most recent sync/redownload that has occurred (call it recentSync: (hash: String, height: Long)). If, during the health check a node sees that there is a difference between any peer’s reported recent snapshot height and recentSync height that is >10, all nodes should download the snapshit with the highest height
