### ISSUE TITLE
Log migration for Operator nodes

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#592]
As Node Operators are onboarded, we will need to modify out current logging infrastructure to support nodes deployed separately. As Operator nodes join a cluster, these nodes should begin sending logs to logstash. We also need to ensure that grafana can load metrics successfully.

DoD
1) Our ELK stack can process operator nodes joining/leaving the network
2) Grafana can properly render metrics
3) Operator nodes register with Logstash and Grafana during deployment

**Comment by marcinwadon** [comment]
I think the ticket is no longer relevant, we're not using ELK on the mainnet
