### ISSUE TITLE
Node Operator Deploy 

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#594]
Node operators will require a new deploy method similar to our terraform scripts, however for one node to join a cluster. Ideally these should be wrapped in shell scripts to automate issuing command to join seed node so it's a one-script deploy process for bringing up a new node and joining the existing cluster. Eventually we will want to update this script to successfully complete #592, #591 and #593. However for now, we should focus on ensuring that the attached Walkthrough is automated via a deploy script

DoD
1) the attached Walkthrough is automated via script
[Node Operator Deployment Manual.pdf](https://github.com/Constellation-Labs/constellation/files/3663822/Node.Operator.Deployment.Manual.pdf)

**Comment by buckysballs** [comment]
Couple of updates from the mtg:

1) For testing, lets define our success criteria as joining a node via the script to a 3 node cluster
2) We can deploy a 3 node cluster via `full-deploy.sh` within the Constellation repo, so you'll want to clone from here. Full deploy takes command line args ala:
`./deploy/compute/terraform/full-deploy.sh NAME_OF_CLUSTER NUM_NODES`

Specifically, for a 3 node this should work
`./deploy/compute/terraform/full-deploy.sh 3-node-test 3`

The script builds a jar directly from the local project then sends to GCP, so in addition to the terraform dependencies, java scala and sbt need to be installed. Building the first time may take up to an hour or so because sbt is caching all your dependencies within the .ivy2 folder, but compiling will take a couple minutes from then on.

**Comment by zaemliss** [comment]
Perfect, thank-you.

I'm going to stab at this over the weekend.

Cheers,
Chris


Christopher Black

www.zaxa.ca



-- Note de confidentialité --

Ce message électronique et toutes pièces jointes contiennent des
informations privilégiées et confidentielles.  Si vous n'êtes pas le
destinataire prévu, il est strictement interdit d'utiliser, de copier ou
divulguer les informations ainsi transmises; merci d’en aviser l'expéditeur
et de les supprimer de votre ordinateur.

-- Confidentiality Note --

This email message and any attachments contain privileged and confidential
information.  If you are not the intended recipient, your use, copying or
disclosure of this information is prohibited; please contact the sender and
delete the material from your computer.

**Comment by zaemliss** [comment]
No issues building from scratch. 
Installed dependencies and ran the build.sh which seemed to join a network.

ctrl-C'd out of that and tried the full-deploy script

Running the full-deploy.sh ran into some issues:
```
./deploy/compute/terraform/restart.sh: line 8: pssh: command not found
./deploy/compute/terraform/restart.sh: line 9: pssh: command not found
./deploy/compute/terraform/restart.sh: line 10: pssh: command not found
```
and a failed test at the end:
```
[info] ClusterStartTest:
[info] Cluster integration
[info] - should ping a cluster, check health, go through genesis flow *** FAILED ***
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:366)
[info]   at scala.None$.get(Option.scala:364)
[info]   at org.constellation.ComputeTestUtil$.createApisFromIpFile(ClusterComputeManualTest.scala:83)
[info]   at org.constellation.ClusterStartTest.$anonfun$new$1(ClusterStartTest.scala:33)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info] ScalaTest
[info] Run completed in 5 seconds, 96 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

**Comment by zaemliss** [comment]
installing pssh (will make it part of dependencies)

**Comment by zaemliss** [comment]
pssh = parallel-ssh. Need to check for it and symlink to avoid errors

**Comment by buckysballs** [comment]
If I had to guess, terraform can't find pssh. `which pssh`?

**Comment by zaemliss** [comment]
```bash
~/constellation/ui ~/constellation
[info] Loading settings for project ui-build from plugins.sbt ...
[info] Loading project definition from /root/constellation/ui/project
[info] Loading settings for project ui from build.sbt ...
[info] Set current project to ui (in build file:/root/constellation/ui/)
[success] Total time: 0 s, completed Oct 1, 2019 5:53:42 AM
[info] Compiling 3 Scala sources to /root/constellation/ui/target/scala-2.12/classes ...
[warn] there was one deprecation warning (since 0.6.20); re-run with -deprecation for details
[warn] one warning found
[info] Done compiling.
[info] Full optimizing /root/constellation/ui/target/scala-2.12/ui-opt.js
[info] Closure: 0 error(s), 0 warning(s)
[success] Total time: 125 s, completed Oct 1, 2019 5:55:47 AM
~/constellation
[info] Loading settings for project constellation-build from scalapb.sbt,plugins.sbt ...
[info] Loading project definition from /root/constellation/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to constellation (in build file:/root/constellation/)
[info] Compiling 1 Scala source to /root/constellation/target/scala-2.12/classes ...
[info] Done compiling.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Strategy 'concat' was applied to a file (Run the task at debug level to see details)
[info] Strategy 'deduplicate' was applied to 4 files (Run the task at debug level to see details)
[info] Strategy 'discard' was applied to 143 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 2 files (Run the task at debug level to see details)
[info] Packaging /root/constellation/target/scala-2.12/constellation-assembly-1.0.12.jar ...
[info] Done packaging.
[success] Total time: 75 s, completed Oct 1, 2019 5:57:23 AM
Restarting ./terraform/default-dev/hosts
Done restarting
[info] Loading settings for project constellation-build from scalapb.sbt,plugins.sbt ...
[info] Loading project definition from /root/constellation/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to constellation (in build file:/root/constellation/)
[info] Compiling 1 Scala source to /root/constellation/target/scala-2.12/classes ...
[info] Done compiling.
2019-10-01 05:58:12,501 [pool-5-thread-1] [] INFO  o.c.crypto.KeyUtils$ - Insert provider return 1
[info] ClusterStartTest:
[info] Cluster integration
[info] - should ping a cluster, check health, go through genesis flow *** FAILED ***
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:366)
[info]   at scala.None$.get(Option.scala:364)
[info]   at org.constellation.ComputeTestUtil$.createApisFromIpFile(ClusterComputeManualTest.scala:83)
[info]   at org.constellation.ClusterStartTest.$anonfun$new$1(ClusterStartTest.scala:33)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info] ScalaTest
[info] Run completed in 5 seconds, 158 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         org.constellation.ClusterStartTest
[error] (IntegrationTest / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 29 s, completed Oct 1, 2019 5:58:14 AM
```

**Comment by zaemliss** [comment]
the pssh and gsutil issues are fixed via symlink and installation and a server reboot but the script still fails at cluster integration.
(notes on: https://github.com/zaemliss/Constellation)

**Comment by marcinwadon** [comment]
Hey @zaemliss, the latter test is failing (`NoSuchElementException`) because you have no `$HOSTS_FILE` environmental variable. Such variable is being set as a path to the hosts file, with all nodes IPs. Line 33 in `deploy/compute/terraform/start-cluster.sh`.
```
./ips_to_hosts_file.sh > ./hosts
```
where `ips_to_hosts_file.sh` is:
```
#!/usr/bin/env sh
terraform output -json instance_ips | jq ".[]" -r
```

**Comment by zaemliss** [comment]
added that, thanks. Still failed at the same place.

**Comment by zaemliss** [comment]
./deploy/compute/terraform/../assemble-upload.sh: line 7: gsutil: command not found
will look at this as well as it's the first error and possibly the root of the issue

**Comment by marcinwadon** [comment]
Ok, so if you're running `full-deploy` and still have an issues in the last step, it means that the terraform step haven't executed properly. What will happen when you'll launch `terraform init` and `terraform apply` manually?

**Comment by zaemliss** [comment]
giving not found errors. Terraform is apparently not installed. 

Installing and trying again.

**Comment by zaemliss** [comment]
```
root@vultr:~/constellation# terraform init
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
root@vultr:~/constellation# terraform apply

Error: No configuration files

Apply requires configuration to be present. Applying without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run 'terraform destroy' instead.
```

**Comment by marcinwadon** [comment]
Please take a look into `start-cluster.sh` and see how to prepare the terraform configuration and where to launch it. Can we switch to community gitter?

**Comment by zaemliss** [comment]
Hi, logged into Gitter under zaemliss.

Will check out start-cluster.sh this evening
Thanks

Chris



Christopher Black

www.zaxa.ca



-- Note de confidentialité --

Ce message électronique et toutes pièces jointes contiennent des
informations privilégiées et confidentielles.  Si vous n'êtes pas le
destinataire prévu, il est strictement interdit d'utiliser, de copier ou
divulguer les informations ainsi transmises; merci d’en aviser l'expéditeur
et de les supprimer de votre ordinateur.

-- Confidentiality Note --

This email message and any attachments contain privileged and confidential
information.  If you are not the intended recipient, your use, copying or
disclosure of this information is prohibited; please contact the sender and
delete the material from your computer.
