### ISSUE TITLE
Update Terraform for AWS and Stackpath

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#595]
We need to update our current terraform scripts to support both AWS and our new partner StackPath. Should be straightforward.

DoD
1) Terraform can deploy on:
- [x] AWS
- [ ] StackPath

Note: revisit when state channels

**Comment by marcinwadon** [comment]
AWS terraform done under #840

**Comment by marcinwadon** [comment]
Created separate issue for StackPath
