### ISSUE TITLE
Block Explorer

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#596]
We need a backend for both a block explorer and our wallet app. Given that we're storing graph data we will probably want a graph database for more complicated queries, and we could probably be fine with Neo4j (HypergraphDB would be cool when we introduce state channels). We should also have a separate store for quick lookups, probably ES. Given that node operators will be distributed amongst different cloud providers, it might become a headache to try and index data directly from nodes. I would say a good first implementation just indexes data from external storage via a chron job, as long as we can keep latency relatively low. The most important utility is fast lookups for our wallet app so we should probably focus on ES first.

DoD
1) ES instance that indexes from external data store (S3)

**Comment by buckysballs** [comment]
I removed DoD #2, `Graph db for analyzing dag`, which I think should be moved to another ticket.

**Comment by buckysballs** [comment]
Regarding the backend component, serving as an API to the es instance:

![Block explorer (1)](https://user-images.githubusercontent.com/4953237/68711551-b2963d80-054e-11ea-85c6-95644f35d39e.jpg)

we'll want both the wallet and the front end to request data without having to form es queries on the client side. A simple way of implementing the API would be with lambdas and AWS gateway, where the functionality of each endpoint would be to receive query parameters as basic strings, submit as es queries, and handle the response for the client. Specifically for the API, we will require the following endpoints:

/recent_tx
- Given an account string, return most recent transaction that has been accepted by that account, the block that it was contained in, and the associated snapshot hash.

/block_hash
- Given a block hash, return the contents of the corresponding block

/snapshot_hash
- Given a snapshot hash, return the contents of the corresponding snapshot (all blocks contained within the window)

We'll likely wish to expand these endpoints in the future but those will fulfill our needs for now.

**Comment by kpudlik** [comment]
Btw. I have some suggestions to endpoints as these are named incorrectly (at last according to common REST rules I suggest to follow).

For example 

- `/block_hash` does not return hash of the block but Block itself by `hash`, so it should be rather: `/block/{block_hash}`

- `/snapshot_hash` does not return hash of snapshot but Snapshot itself, so it should be: `/snapshot/{snapshot_hash}`

In general it should be: `/{resource-name}/{eventually-subresource-name/{params}`

**Comment by buckysballs** [comment]
Hyphens, not snake-case 🤦‍♂ , right. We have camel case in the API too, don't remember how that happened but we should change that too

**Comment by kpudlik** [comment]
I am not talking about snake_case vs kebab-case but about the structure of endpoint :P

If you want to GET `Block` by passing there `hash` then endpoint should be like this:

`/what-i-want-to-get/{params}`

Here I want to get `block` by passing `hash` param, so:

`/block/{hash}`, for example `GET /block/8348327` where `8348327` is a hash :P
