### ISSUE TITLE
Increasing the "snapshotHeightIntervalConditionNotMet" metric shouldn't increase "snapshotAttempt_failure"

### ISSUE THREAD

**Issue by mchrapek** [Constellation-Labs/constellation#633]
**Description:**
Every time when we increase the `snapshotHeightIntervalConditionNotMet` metric we also increase `snapshotAttempt_failure` metric. 

**Acceptance Criteria:**
Occurrence `snapshotHeightIntervalConditionNotMet` is not a error, we shouldn't increase `snapshotAttempt_failure` metric.
Both metrics should remain.

**Comment by marcinwadon** [comment]
Done
