### ISSUE TITLE
Switch node operators from autogenerating keyPair to keystore

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#638]
For this ticket we drop the support for generating keys on the fly and storing them as a plaintext (`.dag/key` directory). The fallback to old behavior needs to be removed and `terraform/gcp` needs to be configured properly so we can inject keystore path and passwords properly to start the node.

Related issue: https://github.com/Constellation-Labs/constellation/issues/638

**Comment by marcinwadon** [comment]
We have managed to launch the cluster using the production flow (#840), which means we can drop the support of the fallback.
