### ISSUE TITLE
Running node as genesis by parameter flag

### ISSUE THREAD

**Issue by mchrapek** [Constellation-Labs/constellation#659]
After our changes, we are unable to start the node with the `-g` flag, we have to do it through the test.
The `-g` flag means running node as a genesis node.

This task is a part of the #500 task.

**DoD**:
Running node as genesis by flag `java (...) -jar dag.jar -g`.
Correctly initializing account values ​​from a `.csv` file.

**Comment by marcinwadon** [comment]
Done
