### ISSUE TITLE
GCP - Unable to ssh into instance.

### ISSUE THREAD

**Issue by StrannikAD** [Constellation-Labs/constellation#664]
I was having issues ssh'ing into my instance on GCP last night - it was taking a very long time and eventually it failed. I looked at the instance logs and this error message came up:

`Nov  3 22:42:26 anna-node-constellation google-accounts: ERROR Exception calling the response handler. [Errno 28] No space left on device.#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/google_compute_engine/accounts/accounts_utils.py", line 322, in SetConfiguredUsers#012    updated_users.flush()#012  File "/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper#012    return func(*args, **kwargs)#012OSError: [Errno 28] No space left on device#012#012During handling of the above exception, another exception occurred:#012#012OSError: [Errno 28] No space left on device#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/google_compute_engine/metadata_watcher.py", line 200, in WatchMetadata#012    handler(response)#012  File "/usr/lib/python3/dist-packages/google_compute_engine/accounts/accounts_daemon.py", line 285, in HandleAccounts#012    self.utils.SetConfiguredUsers(desired_users.keys())#012  File "/usr/lib/python3/dist-packages/google_compute_engine/accounts/accounts_utils.py", line 325, in SetConfiguredUsers#012    shutil.copy(updated_users_file, self.google_users_file)#012  File "/usr/lib/python3.5/tempfile.py", line 640, in __exit__#012    result = self.file.__exit__(exc, value, tb)#012OSError: [Errno 28] No space left on device
`

My VM has a 20GB disk as per the details below - and I haven't been installing anything new over the last week in order to cause the "No space left on device" error:

![image](https://user-images.githubusercontent.com/22587768/68093270-ee465d00-fee7-11e9-9d9c-88807eea56eb.png)

**Comment by buckysballs** [comment]
Update: looks like dag.log is growing constantly, and app.log limit is 20gb which was the size of @StrannikAD's machine. I think we can solve by modifying logback.xml to reduce app.log and limit dag.log

**Comment by zaemliss** [comment]
temporary fix, creating scheduled jobs to delete the logs:
```
crontab -e
```
chose nano if prompted

paste the following:
```
0 0 * * * find /root/constellation/logs/archived/ -type f -mtime +7 -name '*.gz' -delete
1 0 * * * rm /root/constellation/logs/json_logs/dag.log
2 0 * * * rm /root/constellation/logs/app.log
```
then `CTRL-X, Y, [ENTER]` to exit and save.

this will delete dag.log, app.log and any archived logs older than 7 days at midnight UTC every day.

**Comment by marcinwadon** [comment]
Logback is already fixed, closing the issue
