### ISSUE TITLE
Hierarchical Deterministic Wallet

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#671]
In accordance with #644 we need to implement a Hierarchical Deterministic Wallet, ideally in BIP44 standard, that is creates child keys compatible with our [account structure](https://github.com/Constellation-Labs/constellation/blob/242503d2b4260e82716387661fb36fdf0c7b8a13/keytool/src/main/scala/org/constellation/keytool/KeyUtils.scala#L205) and is implemented using our same [cryptographic primitives](https://github.com/Constellation-Labs/constellation/blob/242503d2b4260e82716387661fb36fdf0c7b8a13/keytool/src/main/scala/org/constellation/keytool/KeyUtils.scala#L58). The best approach may be to overload methods in some existing bitcoin wallet libraries, [bitcoinj](https://github.com/bitcoinj/bitcoinj) and [ACINQ's bitcoin-lib](https://github.com/ACINQ/bitcoin-lib) or perhaps [web3j](https://github.com/web3j/web3j). The goal of this project is an executable that when passed a 12 word mnemonic code, an account hash, and a signable payload, will return the signed payload which was signed by the corresponding account hash as well as corresponding unit tests.

In terms of the derivation path of the BIP44 standard, we've decided on an [coin type of index](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) `1137` (the fine structure constant) with a full path of `M/44H/0H/1137`. 

Note, this should be marked experimental until verification of its compatibility with a BLOS application on a hardware wallet #644 and a prerequisite for testing the implementation of #644. 

Acceptance criteria:
1) Implementation of hd wallet in BIP44 specification with the above derivation path
2) Executable that when passed a 12 word mnemonic code, an account hash, and a signable payload, will return the signed payload which was signed by the corresponding account hash
3) Unit tests for functionality of 1 and 2

**Comment by EdwardTarantulo** [comment]
Should it look like this?

![dag-ledger](https://user-images.githubusercontent.com/57504756/68526419-7069c380-02e4-11ea-95aa-feb61d04d9a3.jpg)

**Comment by coranos** [comment]
started on it:

https://github.com/coranos/blue-app-constellation

no pics yet, but will have some in the coming months as it's integrated with the rest of the ecosystem.

**Comment by timxor** [comment]
Any eta on this or should I find the other one to work on?

**Comment by timxor** [comment]
https://github.com/Constellation-Labs/constellation/issues/644

**Comment by coranos** [comment]
The code is ready, just waiting for constellation to tell me to test it on mainnet.

https://github.com/coranos/blue-app-constellation

**Comment by buckysballs** [comment]
Awesome thanks so much @coranos! I went over your blue-app-constellation yesterday and I noticed that I left out a couple parameters we need in the run length encoding (sorry 🤦‍♂ ) so I [updated](https://github.com/Constellation-Labs/constellation/issues/735#issuecomment-591654791) the [ticket](https://github.com/Constellation-Labs/constellation/issues/735) for our changes on the protocol side to reflect what we need to add. tl;dr we just need to add 3 more fields between amount and salt to be parsed by the BOLOS app, as detailed above.

Also, I went through and made an [initial implementation](https://github.com/Constellation-Labs/constellation/pull/905) of changes to our signing flow to use the run length encoding as a payload. We're going to be testing incorporating those changes in our last sprint before main net and we'll deploy on the testnet for e2e testing beforehand. If you'd like to follow along, this will be slotted for after #887 in the todo column of the [project board](https://github.com/Constellation-Labs/constellation/projects/4).

Also, I've made an initial implementation of a BIP44 hd wallet for Constellation [here](https://github.com/Constellation-Labs/PYBIP44/branches) which we can use for testing (and also the Molly wallet). The keygen should work as intended since we're (essentially) using the same as btc, but I still need to double check that the address generation logic was ported properly (we actually don't need it) but will confirm and share either way. Once I've wrapped up the hd tree I can help make unit tests for blue-app-constellation too.

Anyways, let me know if there are any issues with adding those 3 fields to the payload and I'll share the hd wallet once tested 💪

**Comment by timxor** [comment]
Just @ me where ya need some minor help for anything

**Comment by buckysballs** [comment]
Closing this as crossover of #735
