### ISSUE TITLE
Attempting to connect to Elasticsearch version 7.4.0 - Instance Issue

### ISSUE THREAD

**Issue by StrannikAD** [Constellation-Labs/constellation#679]
I noticed my instance is burning through disk space. When I checked the instance logs, it seems to be a filebeat/elastic search issue.

`Nov 26 05:12:15 anna-node-constellation filebeat[9811]: 2019-11-26T05:12:15.862Z#011INFO#011elasticsearch/client.go:743#011Attempting to connect to Elasticsearch version 7.4.0
Nov 26 05:12:31 anna-node-constellation filebeat[9811]: 2019-11-26T05:12:31.775Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":2260},"total":{"ticks":11320,"time":{"ms":8},"value":11320},"user":{"ticks":9060,"time":{"ms":8}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":7},"info":{"ephemeral_id":"95220a11-300c-4687-9304-411259a4d412","uptime":{"ms":16830034}},"memstats":{"gc_next":44198864,"memory_alloc":23340096,"memory_total":265531120,"rss":-24576},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":2}},"libbeat":{"config":{"module":{"running":0}},"output":{"read":{"bytes":1757},"write":{"bytes":268}},"pipeline":{"clients":1,"events":{"active":4117,"retry":50}}},"registrar":{"states":{"current":2}},"system":{"load":{"1":0.17,"15":0.18,"5":0.19,"norm":{"1":0.0425,"15":0.045,"5":0.0475}}}}}}
Nov 26 05:13:01 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:01.776Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":2260},"total":{"ticks":11320,"time":{"ms":4},"value":11320},"user":{"ticks":9060,"time":{"ms":4}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":7},"info":{"ephemeral_id":"95220a11-300c-4687-9304-411259a4d412","uptime":{"ms":16860035}},"memstats":{"gc_next":44198864,"memory_alloc":23670224,"memory_total":265861248},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":2}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":4117}}},"registrar":{"states":{"current":2}},"system":{"load":{"1":0.17,"15":0.18,"5":0.19,"norm":{"1":0.0425,"15":0.045,"5":0.0475}}}}}}
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.408Z#011ERROR#011pipeline/output.go:100#011Failed to connect to backoff(elasticsearch(https://elasticsearch:9200)): Connection marked as failed because the onConnect callback failed: cannot retrieve the elasticsearch license: could not extract license information from the server response: unknown state, received: 'expired'
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.408Z#011INFO#011pipeline/output.go:93#011Attempting to reconnect to backoff(elasticsearch(https://elasticsearch:9200)) with 379 reconnect attempt(s)
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.408Z#011INFO#011[publisher]#011pipeline/retry.go:189#011retryer: send unwait-signal to consumer
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.408Z#011INFO#011[publisher]#011pipeline/retry.go:191#011  done
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.408Z#011INFO#011[publisher]#011pipeline/retry.go:166#011retryer: send wait signal to consumer
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.408Z#011INFO#011[publisher]#011pipeline/retry.go:168#011  done
Nov 26 05:13:03 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:03.551Z#011INFO#011elasticsearch/client.go:743#011Attempting to connect to Elasticsearch version 7.4.0
Nov 26 05:13:31 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:31.775Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":2270,"time":{"ms":8}},"total":{"ticks":11380,"time":{"ms":56},"value":11380},"user":{"ticks":9110,"time":{"ms":48}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":7},"info":{"ephemeral_id":"95220a11-300c-4687-9304-411259a4d412","uptime":{"ms":16890035}},"memstats":{"gc_next":44212912,"memory_alloc":22344040,"memory_total":266237184},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":2}},"libbeat":{"config":{"module":{"running":0}},"output":{"read":{"bytes":1757},"write":{"bytes":268}},"pipeline":{"clients":1,"events":{"active":4117,"retry":50}}},"registrar":{"states":{"current":2}},"system":{"load":{"1":0.18,"15":0.18,"5":0.19,"norm":{"1":0.045,"15":0.045,"5":0.0475}}}}}}
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.819Z#011ERROR#011pipeline/output.go:100#011Failed to connect to backoff(elasticsearch(https://elasticsearch:9200)): Connection marked as failed because the onConnect callback failed: cannot retrieve the elasticsearch license: could not extract license information from the server response: unknown state, received: 'expired'
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.819Z#011INFO#011pipeline/output.go:93#011Attempting to reconnect to backoff(elasticsearch(https://elasticsearch:9200)) with 380 reconnect attempt(s)
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.820Z#011INFO#011[publisher]#011pipeline/retry.go:189#011retryer: send unwait-signal to consumer
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.820Z#011INFO#011[publisher]#011pipeline/retry.go:191#011  done
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.820Z#011INFO#011[publisher]#011pipeline/retry.go:166#011retryer: send wait signal to consumer
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.820Z#011INFO#011[publisher]#011pipeline/retry.go:168#011  done
Nov 26 05:13:36 anna-node-constellation filebeat[9811]: 2019-11-26T05:13:36.963Z#011INFO#011elasticsearch/client.go:743#011Attempting to connect to Elasticsearch version 7.4.0
Nov 26 05:14:01 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:01.776Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":2280,"time":{"ms":8}},"total":{"ticks":11400,"time":{"ms":12},"value":11400},"user":{"ticks":9120,"time":{"ms":4}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":7},"info":{"ephemeral_id":"95220a11-300c-4687-9304-411259a4d412","uptime":{"ms":16920034}},"memstats":{"gc_next":44212912,"memory_alloc":22618584,"memory_total":266511728},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":2}},"libbeat":{"config":{"module":{"running":0}},"output":{"read":{"bytes":1757},"write":{"bytes":268}},"pipeline":{"clients":1,"events":{"active":4117,"retry":50}}},"registrar":{"states":{"current":2}},"system":{"load":{"1":0.19,"15":0.18,"5":0.18,"norm":{"1":0.0475,"15":0.045,"5":0.045}}}}}}
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.726Z#011ERROR#011pipeline/output.go:100#011Failed to connect to backoff(elasticsearch(https://elasticsearch:9200)): Connection marked as failed because the onConnect callback failed: cannot retrieve the elasticsearch license: could not extract license information from the server response: unknown state, received: 'expired'
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.726Z#011INFO#011pipeline/output.go:93#011Attempting to reconnect to backoff(elasticsearch(https://elasticsearch:9200)) with 381 reconnect attempt(s)
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.726Z#011INFO#011[publisher]#011pipeline/retry.go:189#011retryer: send unwait-signal to consumer
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.726Z#011INFO#011[publisher]#011pipeline/retry.go:191#011  done
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.727Z#011INFO#011[publisher]#011pipeline/retry.go:166#011retryer: send wait signal to consumer
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.727Z#011INFO#011[publisher]#011pipeline/retry.go:168#011  done
Nov 26 05:14:25 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:25.870Z#011INFO#011elasticsearch/client.go:743#011Attempting to connect to Elasticsearch version 7.4.0
Nov 26 05:14:31 anna-node-constellation filebeat[9811]: 2019-11-26T05:14:31.775Z#011INFO#011[monitoring]#011log/log.go:145#011Non-zero metrics in the last 30s#011{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":2280,"time":{"ms":4}},"total":{"ticks":11400,"time":{"ms":8},"value":11400},"user":{"ticks":9120,"time":{"ms":4}}},"handles":{"limit":{"hard":4096,"soft":1024},"open":7},"info":{"ephemeral_id":"95220a11-300c-4687-9304-411259a4d412","uptime":{"ms":16950033}},"memstats":{"gc_next":44212912,"memory_alloc":22892520,"memory_total":266785664},"runtime":{"goroutines":28}},"filebeat":{"harvester":{"open_files":1,"running":2}},"libbeat":{"config":{"module":{"running":0}},"output":{"read":{"bytes":1757},"write":{"bytes":268}},"pipeline":{"clients":1,"events":{"active":4117,"retry":50}}},"registrar":{"states":{"current":2}},"system":{"load":{"1":0.11,"15":0.17,"5":0.16,"norm":{"1":0.0275,"15":0.0425,"5":0.04}}}}}}
`

**Comment by marcinwadon** [comment]
@buckysballs
```
In order to enable security it is necessary to have either a Gold or Platinum subscription, or a trial license enabled via Kibana or API.
```
Looks like we had a trial license
