### ISSUE TITLE
Clear SOE mem pool along with checkpoint block removal

### ISSUE THREAD

**Issue by marcinwadon** [Constellation-Labs/constellation#693]
Currently we're not clearing SOE mem pool which triggers the time-based eviction. We should remove SOE from the mem pool along with the corresponding checkpoint block(s) removal.

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/4959931/70801782-1ad77980-1db0-11ea-8e9c-d30e6bb12f01.png">

**Comment by mchrapek** [comment]
Info from @buckysballs :
safe place to remove SOE’s from memory would be during the step when writing snapshots to disk. Once a snapshot has been accepted across all peers, we don’t need the SOE’s referencing those blocks anymore
