### ISSUE TITLE
Installer/Dockerfile for client wallet exe

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#700]
We're running into issues deploying the client wallet in different environments, and it looks like the main cause may be the Java version used when running the jar. It was compiled with java version 1.8.0_172 and I’ve had success running it with that java version on mine and an instance on gcp. But I’ve noticed that in any java version higher than 1.8.0_231 (I believe) it throws an exception and calls a library that doesn’t follow the call stack in the project (at least with that java version). One thing to note too is that the Dockerfile might need to set a java.security credential for bouncey-castle. 

For background: the client-wallet is currently contained within this open pr: https://github.com/Constellation-Labs/constellation/pull/677 

Dod:
- Installer script and/or Dockerfile for running the client-wallet exe
- Executables can be run successfully after install or from a docker container
- An example command for testing is provided below, which should create a keypair and store it in the directory provided by keystore

`java -cp /Users/wyatt/constellation/target/scala-2.12/constellation-assembly-1.0.12.jar org.constellation.keytool.KeyTool --keystore=/Users/wyatt/test.txt --alias=alias --storepass=storepass --keypass=keypass`

**Comment by marcinwadon** [comment]
Hey,

I’ve checked all wallet methods "in docker” and everything is working:
1. I've created a keystore (public and private key) using a keytool docker image
2. I've exported pub and priv key decrypted into strings (wallet: ExportDecryptedKeys main class)
3. Generated an account address from public key (wallet: GenerateAddress main class)
4. Created a new transaction using those pub/priv keys, last (empty) tx, account address. (wallet: CreateNewTransaction main class)

All of these I’ve done using docker keytool/wallet image, so I assume it’s working properly.

cc: @buckysballs @grvlle @ThomasvandenBroek
