### ISSUE TITLE
Add requirement for peers to have an account balance

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#701]
Add requirement for peers to have an account balance greater than a fixed "staking" amount, which will be a hard coded/configurable value, currently 250,000 $DAG. 

We will need to check this value when joining the cluster. For simplicity, we can prevent nodes from spending beyond this amount while joined to the cluster

DOD)
- Added balance check during join process of joining node's address balance
- Add transaction validation logic, preventing nodes from reducing balance below the staking amount while joined to the cluster

**Comment by ThomasvandenBroek** [comment]
Estimate 2days
