### ISSUE TITLE
Add "Stardust" address to rewards distribution

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#702]
As part of our governance approach, part of our rewards (10%) will need to go to an address that will be redeemable by the Stardust Collective, which is a community run organization that will deploy these rewards for improvements voted on by the community.

For security/custodianship I think it makes sense to hardcode a specific address that does not exactly correspond to a keypair to prevent hacks, or need for custodianship. And we can redeploy when to share those funds.

Dod)
- Rewards are distributed to a dedicated Stardust address, during the rewards distribution process.
- Method for creating a dedicated Stardust address which conforms to validation rules but does not associate with a keypair. Wyatt will provide.

**Comment by ThomasvandenBroek** [comment]
Estimate: 1 day
