### ISSUE TITLE
Long running integration test

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#704]
For long term integration testing, we should decouple the RandomTransactionManager from nodes and have the Transaction stream pass through an instance of the load balancer. This would require creating a separate app for the RandomTransactionManager and adding configuration to sending the Transactions created tot he load balancer. 

Dod)
- Refactor Random Transaction Manager into standalone app that feeds into loadbalancer, and also sends double spends. 
- Script for generating and saving key pairs en-masse, directory structure etc. We should shoot for 10,000. Note: we should move address cache data to a db, the total could be millions
- Service for loading key pairs, using in random transaction manager. 
- Periodic check of validator rewards: sum each snapshot, sum total

**Comment by marcinwadon** [comment]
### Prerequirements:
- `cl-node.jar` with constellation node to be tested on the cluster
- Number of wallets (`n`) - we should aim for at least 10k
- Number of nodes (`m`)
- Configuration for the nodes (aka intervals, delays, etc)

### How to spin up a test cluster:
- Using `cl-keytool.jar` generate `n` key pairs for wallets and `m` key pairs for nodes
- Prepare CSV file to fill initial balances for the cluster (address from each keypair -> initial balance)
- Launch 1 node in the genesis mode using prepared csv file (instance on AWS with `cl-node.jar`, csv file and keypair)
- Launch the rest of the nodes and join to the first one
- Wait for `ready` state for each node
- Launch a loadbalancer as a standalone scala app and connect it to the created cluster

### What should be checked periodically:
- JVM Heap and CPU usage
- Checkpoint acceptance rate
- Snapshot alignment check
- Exceptions/Errors on the cluster
- Data migration pipeline
- Rewards (either modifying /balance endpoint to return balance from rewards or keeping track of nodes' balances) - to be defined
- Stardust balance (as a part of rewards)

### Scenarios:

**For each scenario, transactions should be created from node to wallet, wallet to node and wallet to wallet**

#### Scenario 1: (single transaction at a time)
- Create one transaction at a time
- Verify both source and destination addresses' balances

#### Scenario 2: (transactions in batch)
- Create transactions in batch
- Verify all balances after all of them have been processed

#### Scenario 3: (double spend)
- Create double spend transactions and verify if addresses have been banned
- Create few more (valid) transactions and verify if all of them have been ignored

#### Scenario 4: (node restart)
- Safely turn off a node (shutdown with leaving time)
- Turn it on after few minutes
- Verify that node is able to perform consensus rounds and snapshots and has been properly connected to the cluster
