### ISSUE TITLE
Auth from elb to API and remove "faucet" endpoints

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#707]
Currently we have some endpoints that are used for testing that can cause security issues if not removed or access to them is not authenticated. 

Specifically the endpoints to remove are /send on the API and /faucet on the PeerAPI. The endpoint we need to add authentication to is /transaction on the API, which should authenticate the source as coming from the ELB. 

DoD)
- Removal of endpoints above
- Authentication on the /Transaction endpoint, allowing only Transactions forwarded from the load balancer.

**Comment by marcinwadon** [comment]
Done before mainnet except the auth for /tx endpoint which I think is not still valid
