### ISSUE TITLE
Confirm same starting version

### ISSUE THREAD

**Issue by ThomasvandenBroek** [Constellation-Labs/constellation#713]
DoD:

Agree on starting version make sure that we keep it consistent across all release channels

tl;dr use hash of op codes from sbt assembly, should be in /buildInfo but double check. We just need to modify validateGitCommitHash to check the string of that hash. I think BuildInfoPlugin in build.sbt has the hash we need, but if not there is this https://github.com/josephearl/sbt-verify

EDIT:

Just calculate the hash of BuildInfo and compare it

**Comment by kpudlik** [comment]
Hash is different when sending it via API
