### ISSUE TITLE
Follow up questions to: Constellation Network State of the Union

### ISSUE THREAD

**Issue by INVESTOR-HERE** [Constellation-Labs/constellation#724]
Dear all, recently watched thisvideo and have some follow up questions. 
https://www.youtube.com/watch?v=5EOt3nRzm88

1) Could you please point me to a tutorial / documentation / reference architecture how to implement a Constellation data pipeline based on streaming data sources, Kafka for example? (Minute 12)

2) Could you point me to some screenshots of the data pipeline user interface?
  
3) Could you please point to the some documentation which explains additional security benefits of Constellation compared to existing security approaches? Specially compared to encryption in motion and rest and certificates on the IoT devices and checksum / hashing of data?
https://security.stackexchange.com/questions/197911/are-hashes-a-reliable-method-of-ensuring-a-file-has-not-been-tampered-with

4) As mentioned data cleansing and preparation typically consumes quite some time before AI / Data science can happen. However, this is still the prerequisite before the data is served in the Constellation topology and Data Scientists are able to focus on the science part of their job. If Constellation provides this task / service in the Data Preparation Pipeline and the data is served in a “plugin” fashion, the following question comes into my mind. How will Constellation get the deep domain expertise and data model knowledge of the required source systems, which is mandatory for data preparation pipelines?  (Around 15:35)

5)	Any plans to implement ISO standards?  
https://www.iso.org/isoiec-27001-information-security.html
https://www.iso.org/obp/ui/#iso:std:iso-iec:38505:-1:ed-1:v1:en

6) Which datasets or data domains are planned to be contributed by the 750 node applicants in 2020?  Does running a node include providing datasets as well in general? Any metrics or forecasts for the planned usage, specifically curated datasets or data models, of the nodes in 2020 available? 

+ In addition referring to this video (Tech Stack Integration)
https://www.youtube.com/watch?v=L8pI4P0_53I

7. Could you please point me to a tutorial / documentation how to connect Constellation to the data-management stack (Spark / MongoDB)? (Minute 10)

8. How does Constellation help or ensure data is not tampered in the (traditional) data management stack or storage layers after being processed and stored in Constellation (S3/Object-Storage)? 

9. The timeline or roadmap for publishing the APIs / swagger definitions for developers?

Found this interview:
4.3 Spore Technologies — Data Validation and Infrastructure Tools
Spore Technologies — This is our proprietary pay-only platform of licensed state channels: microservice platform that provides a hosted and UX enabled application for SME’s to build distributed applications, state channels, on a decentralized network (The Network) similar to similar to Splunk and 
Databricks.
https://medium.com/@benjorgensen/an-industry-for-the-future-a-company-for-a-future-industry-e96eabf149ae

https://constellationnetwork.io/technology/spore-platform/

My question goes into the direction of business model / monetization. 
1) Will DAG token holders directly benefit from the Spore technologies pay-only platform, e.g. benefit from the monetization of the Constellation Protocol with Spore? Will there be direct conversion from Spore license/consumption revenue (SaaS) to the tokens to benefit the token holders? Is there a whitepaper which describes the Enterprise Business Model more detailed, comparable to the Token Economics Whitepaper? 
2) Is Spore technologies a different legal entity compared to Constellation? 
3) Will the Spore technologies products be open-sourced, e.g. decentralized, or will they be closed-source and proprietary (e.g. centralized)? 
4) Is Spore technologies mandatory to implement the data pipeline use-case and is Spore mandatory for the USAF use-case?

Thank you!

****

**Comment by tubgirl** [comment]
Yeah I have no clue what this is. Maybe Ben or Wyatt knows?
