### ISSUE TITLE
Node rejects requests made from the same IP it is on

### ISSUE THREAD

**Issue by mchrapek** [Constellation-Labs/constellation#726]
I needed information from a secured endpoint, and I wasn't connected to a cluster. I noticed:

Node rejects requests made from the same IP it is on. 
Node deployed on IP: `34.94.71.14`  when I try to execute a secured endpoint I get `Reject unknown ip: 34.94.71.14`. 

Node should add own IP as known IP during start.

**Comment by marcinwadon** [comment]
@mchrapek Don't you have those information on the node itself? Why you need to get those data by own API?
