### ISSUE TITLE
Installer Scripts

### ISSUE THREAD

**Issue by buckysballs** [Constellation-Labs/constellation#733]
We need to create installer scripts for the wallet executables. These would mainly be for downloading the dependencies required to run the executable jar files, for each operating system. The operating systems we need to support are Ubuntu, Osx and Windows. 

For reference, we currently have [Dockerfiles](https://github.com/Constellation-Labs/constellation/blob/ef092f44ecfec86f23fd1ccbf545d372aee1210d/docker/wallet/Dockerfile) for the executables.

DoD) Installer scripts for downloading dependencies and the jar files for the wallet executables, for Ubuntu, Osx and Windows.

**Comment by mchrapek** [comment]
Script requirements:
1. Java version check (1.8 =< )
2. Check if cryptography is enabled 
``$JAVA_HOME/bin/jrunscript -e 'print (javax.crypto.Cipher.getMaxAllowedKeyLength("RC5") >= 256);'`
3. Check if `JAVA_HOME` is set
4. Unzip files
5. Launching binary files (if it is possible)
