### ISSUE TITLE
Create RedownloadService

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#821]
Create a RedownloadService to fulfil the following process:

![image](https://user-images.githubusercontent.com/9077743/73953752-2c955300-4901-11ea-8b0c-17673280c92c.png)

- Periodic check for majority snapshots proposals of the peers and storing information about the snapshot in `Map[Height, (Id, Hash)]` - for simplicity, we'll postpone adding reputation in that place and we won't use it currently to select the majority snapshot. it will be changed later
- Check for the global majority snapshot hash
- Check for the alignment of the majority snapshot hash
- Trigger redownload (calculate diff, download needed snapshots, **do not remove snapshots from disk for now**)
- Store own proposals as `Map[Height, Hash]` and **never modify stored heights! (because proposals are immutable by design)**
- Store backup of own proposals on disk and send to the cloud if enabled
- Cover by unit tests all the cases
- Write an integrate test (one or more) to verify if the re-download process works correctly and the test cluster converges to the common point

**Comment by marcinwadon** [comment]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/4959931/74641545-c5ce3000-5171-11ea-96e2-d6574e6d442f.png">
