### ISSUE TITLE
Adjust Rewards to Redownload

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#887]
There are 2 cases when Rewards fail because of redownload:

### Missing observation cache
After redownload we remove incorrect snapshots and we download correct ones which are missing. So we need to put observations of redownloaded snapshots into RewardsManager

### When node goes too far
Majority: ABCDEF
Node:      ABCDEFGHIJKLMNOP
snapshotHeightRedownloadDelayInterval: 6

so when Node goes too far then during acceptance of `L` (non-majority snapshot) we are rewarding `G` (non-majority snapshot) because it is delayed by `snapshotHeightRedownloadDelayInterval` but still incorrect according to majority :disappointed: 

When we create `M` we are rewarding `H` etc.

so if it diverges too much (more than `snapshotHeightRedownloadDelayInterval`) then we still do rewards for incorrect snapshots
We had an idea of rewarding only majority snapshots because these should never change. But it must be probably the clear majority

**Comment by buckysballs** [comment]
This has been partially implemented by #891
