### ISSUE TITLE
Add endpoints for the highest majority snapshot

### ISSUE THREAD

**Issue by marcinwadon** [Constellation-Labs/constellation#982]
~- [ ] Add endpoint which will return the latest majority state sorted by height~
~- [ ] Add endpoint which will return the latest majority snapshot **(to be defined in which format)**~

**Redefined:**
- [x] Add endpoint to the block explorer to return the highest snapshot

**Comment by buckysballs** [comment]
Let's change /snapshot endpoint to return a maxBy height query when supplied an empty string as the route param
